apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsc
  template:
    metadata:
      labels:
        app: vsc
    spec:
      containers:
      - image: okteto.dev/vsc:latest
        name: vsc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f61ec21c-2bd0-4c54-bb2e-36809930b295"
        - name: Vless_Path
          value: "/wzovy372"
        - name: Vmess_UUID
          value: "f61ec21c-2bd0-4c54-bb2e-36809930b295"
        - name: Vmess_Path
          value: "/enksd456"
        - name: Share_Path
          value: "/v2link"
